### ISSUE TITLE
完善 Paginator 

### ISSUE THREAD

**Issue by Macaulish64** [eatradish/saki.li#5]
似乎分页器page-nav没有对应的样式，所以出来分页的时候比较丑。（因为巨巨的主页只有10篇文章所有暂时没有出现分页，我看不到效果。不知道是不是我哪里忘了改所以出了问题）
另外，个人认为归档的时候就不要需要分页。
同时，分页参数(在hexo默认的配置文件里是config.per_page)没有用上，目前似乎是默认10个文章一页。
以上

**Comment by eatradish** [comment]
归档的问题，可以在站点配置文件下暂时添加这两行解决问题：

```
archive_generator:
  per_page: 0
```

至于 index 的分页，目前 hexo 的分页插件似乎不能令我满意

**Comment by eatradish** [comment]
另外，对于 index 的分页，正确的设置应该像是这样：

```
index_generator:
  path: ''
  per_page: 3
  order_by: -date
```

至于分页的样式问题，我的想法是在首页最下方有一个「较旧的文章」按钮，点击后在主页下面加载出较旧的文章
